# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.support::lang.controllers.ticketgroups.label

# Model Form Field configuration
form: $/waka/support/models/ticketgroup/fields.yaml

# Model Class name
modelClass: Waka\Support\Models\TicketGroup

# Default redirect location
defaultRedirect: waka/support/ticketgroups

# Create page
create:
    title: backend::lang.form.create_title
    redirect: waka/support/ticketgroups/update/:id
    redirectClose: waka/support/ticketgroups
    form: $/waka/support/models/ticketgroup/fields_create.yaml

# Update page
update:
    title: backend::lang.form.update_title
    redirect: waka/support/ticketgroups/update/:id
    redirectClose: waka/support/ticketgroups

# Preview page
preview:
    title: backend::lang.form.preview_title
