# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.support::lang.controllers.tickets.label

# Model Form Field configuration
form: $/waka/support/models/ticket/fields.yaml

# Model Class name
modelClass: Waka\Support\Models\Ticket

# Default redirect location
defaultRedirect: waka/support/tickets

# Create page
create:
    title: backend::lang.form.create_title
    redirect: waka/support/tickets/update/:id
    redirectClose: waka/support/tickets
    form: $/waka/support/models/ticket/fields_create.yaml

# Update page
update:
    title: backend::lang.form.update_title
    redirect: waka/support/tickets/update/:id
    redirectClose: waka/support/tickets

# Preview page
preview:
    title: backend::lang.form.preview_title
