# ===================================
# Filter Scope Definitions
# ===================================
scopes:
    ticketGroups:
        label: Groupes
        conditions: ticket_group_id in (:filtered)
        modelClass: Waka\Support\Models\TicketGroup
        nameFrom: name
    status:
        label: Etat
        conditions: state in (:filtered)
        modelClass: Waka\Support\Models\Ticket
        options: listAllWorkflowState
        nameFrom: name
    user:
        label: waka.support::ticket.user
        modelClass: Backend\Models\User
        nameFrom: full_name
        conditions: user_id in (:filtered)
    type:
        label: waka.support::ticket.ticket_type
        modelClass: Waka\Support\Models\TicketType
        nameFrom: name
        conditions: ticket_type_id in (:filtered)
    nextuser_me:
        label: waka.support::ticket.nextuser_me
        type: checkbox 
        default: true 
        scope: nextUser
    only_active:
        label: waka.support::ticket.only_active
        type: checkbox
        default: true
        scope: active
    is_sleeping:
        label: waka.support::ticket.is_sleeping
        type: checkbox
        default: true
        scope: isNotSleeping
    facturable:
        label: waka.support::ticket.facturable
        type: checkbox
        scope: isFacturable 
    
