datasource: 
    ticket:
        label: Ticket
        code: ticket
        test_id: 1
        author: Waka
        plugin: Support
        name : Ticket
        class: Waka\Support\Models\Ticket
        relations:
            parent:
                label: ticket Parent
            user: 
                label: User
            next: 
                label: User
            ticket_type: 
                label: Type
            ticket_group: 
                label: Group de ticket
                
    ticket_group:
        label: Groupes de ticket
        class: Waka\Support\Models\TicketGroup

    next:
        hidden: true
        label: utilsateur suivant
        class: Backend\Models\User
        attributes: wcli/wconfig/models/user/attributes.yaml
        outputName: full_name

    parent:
        hidden: true
        label: Ticket parent
        class: Waka\Support\Models\Ticket

    ticket_type:
        label: Type de tickets
        class: Waka\Support\Models\TicketType
        controller: waka/support/tickettypes