ticket_w:
    type: state_machine
    metadata: 
        name: waka.support::ticket_w.name 
        com: waka.support::ticket_w.com 
        cron_auto_time: 22h30
        rulesSets:
            default:
                fields:  
                    support_user: required              
                    support_client: required              
                messages: waka.support::ticket_w_errors

        scopes:
            running:
                label: waka.support::ticket_w.scopes.running
                value: [draft,wait_support,wait_managment,running, validated,sleep]             
            runningNotSleeping:
                label: waka.support::ticket_w.scopes.runningNotSleeping
                value: [draft,wait_support,wait_managment,running, validated]             
            closed:
                label: waka.support::ticket_w.scopes.closed
                value: [archived,abdn]             
    marking_store:
        type: single_state
        property: state
    supports:
        - \Waka\Support\Models\Ticket
    places:
        draft:
            metadata:
                label: waka.support::ticket_w.places.draft 
                icon: wicon-pencil2
                hidden_fields: [awake_at]
        wait_support:
            metadata:
                label: waka.support::ticket_w.places.wait_support 
                com: waka.support::ticket_w.places.comments.wait_support 
                icon: icon-clock-o
                hidden_fields: [awake_at]
        wait_managment:
            metadata:
                label: waka.support::ticket_w.places.wait_managment 
                com: waka.support::ticket_w.places.comments.wait_managment 
                icon: icon-clock-o
                hidden_fields: [awake_at]
        running:
            metadata:
                label: waka.support::ticket_w.places.running 
                icon: icon-cogs
                hidden_fields: [awake_at]
        validated:
            metadata:
                label: waka.support::ticket_w.places.validated 
                icon: icon-check
                hidden_fields: [awake_at]
        sleep:
            metadata:
                label: waka.support::ticket_w.places.sleep 
                cron_auto: [sleep_to_wait_support]
                icon: icon-bed
        archived:
            metadata:
                label: waka.support::ticket_w.places.archived 
                icon: icon-cubes
                hidden_fields: [awake_at]
        abdn:
            metadata:
                label: waka.support::ticket_w.places.abdn 
                icon: icon-trash-o
                hidden_fields: [awake_at]
    initial_places: draft  # or set to an array if multiple initial places
    transitions:
        wait_support_to_abdn:
            metadata: 
                label: waka.support::ticket_w.trans.wait_support_to_abdn 
                button: waka.support::ticket_w.trans.buttons.wait_support_to_abdn 
                redirect: "redirect:1"
                color: danger
                fncs:
                    isCreatorAsking:
                        type: gard
            from: wait_support
            to: abdn
        wait_managment_to_abdn:
            metadata: 
                label: waka.support::ticket_w.trans.wait_managment_to_abdn 
                button: waka.support::ticket_w.trans.buttons.wait_managment_to_abdn 
                redirect: "redirect:1"
                color: danger
                fncs:
                    isCreatorAsking:
                        type: gard
            from: wait_managment
            to: abdn
        validated_to_archived:
            metadata: 
                label: waka.support::ticket_w.trans.validated_to_archived 
                button: waka.support::ticket_w.trans.buttons.validated_to_archived 
                redirect: "close:1"
            from: validated
            to: archived
        to_archived_factu:
            metadata: 
                label: waka.support::ticket_w.trans.to_archived_factu 
                button: waka.support::ticket_w.trans.buttons.to_archived_factu 
                hidden: true
                fncs:
                    createChildTicket:
                        type: enter
            from: 
                - wait_managment
                - wait_support
            to: archived
        wait_support_to_wait_managment:
            metadata: 
                label: waka.support::ticket_w.trans.wait_support_to_wait_managment 
                button: waka.support::ticket_w.trans.buttons.wait_support_to_wait_managment 
                redirect: "redirect:1"
                fncs:
                    isSupport:
                        type: gard
                    sendNotification:
                        type: prod
                        args:
                            code: waka.support::new_ticket
                            mode: client
            from: wait_support
            to: wait_managment
        running_to_wait_managment:
            metadata: 
                label: waka.support::ticket_w.trans.running_to_wait_managment 
                button: waka.support::ticket_w.trans.buttons.running_to_wait_managment 
                redirect: "close:1"
                fncs:
                    isSupport:
                        type: gard
            from: running
            to: wait_managment
        wait_support_to_sleep:
            metadata: 
                label: waka.support::ticket_w.trans.wait_support_to_sleep 
                button: waka.support::ticket_w.trans.buttons.wait_support_to_sleep 
                fncs:
                    isSupport:
                        type: gard
                    removeTicketGroup:
                        type: enter
                    askSleep:
                        type: prod
            from: wait_support
            to: sleep
        wait_managment_to_sleep:
            metadata: 
                label: waka.support::ticket_w.trans.wait_managment_to_sleep 
                button: waka.support::ticket_w.trans.buttons.wait_managment_to_sleep 
                fncs:
                    removeTicketGroup:
                        type: enter
                    askSleep:
                        type: prod
            from: wait_managment
            to: sleep
        wait_support_to_running:
            metadata: 
                label: waka.support::ticket_w.trans.wait_support_to_running 
                button: waka.support::ticket_w.trans.buttons.wait_support_to_running 
                redirect: "redirect:1"
                fncs:
                    isSupport:
                        type: gard
            from: wait_support
            to: running
        wait_managment_to_wait_support:
            metadata: 
                label: waka.support::ticket_w.trans.wait_managment_to_wait_support 
                button: waka.support::ticket_w.trans.buttons.wait_managment_to_wait_support 
                redirect: "close:1"
                fncs:
                    sendNotification:
                        type: prod
                        args:
                            code: waka.support::new_ticket
                            mode: support
            from: wait_managment
            to: wait_support
        sleep_to_wait_support:
            metadata: 
                label: waka.support::ticket_w.trans.sleep_to_wait_support 
                button: waka.support::ticket_w.trans.buttons.sleep_to_wait_support 
                redirect: "redirect:1"
                fncs:
                    isAwakable:
                        type: gard
                    cleanAwake:
                        type: enter
            from: sleep
            to: wait_support
        draft_to_wait_managment:
            metadata: 
                label: waka.support::ticket_w.trans.draft_to_wait_managment 
                button: waka.support::ticket_w.trans.buttons.draft_to_wait_managment 
                redirect: "redirect:1"
                fncs:
                    isSupport:
                        type: gard
                    sendNotification:
                        type: prod
                        args:
                            code: waka.support::new_ticket
                            mode: client
            from: draft
            to: wait_managment
        draft_to_wait_support:
            metadata: 
                label: waka.support::ticket_w.trans.draft_to_wait_support 
                button: waka.support::ticket_w.trans.buttons.draft_to_wait_support 
                redirect: "redirect:1"
                fncs:
                    sendNotification:
                        type: prod
                        args:
                            code: waka.support::new_ticket
                            mode: support
            from: draft
            to: wait_support
        wait_managment_to_validated:
            metadata: 
                label: waka.support::ticket_w.trans.wait_managment_to_validated 
                button: waka.support::ticket_w.trans.buttons.wait_managment_to_validated 
                com: waka.support::ticket_w.trans.comments.wait_managment_to_validated 
                redirect: "close:1"
                color: success
                fncs:
                    isClient:
                        type: gard
                    sendNotification:
                        type: prod
                        args:
                            code: waka.support::new_ticket
                            mode: support
            from: wait_managment
            to: validated
        draft_to_validated:
            metadata: 
                label: waka.support::ticket_w.trans.draft_to_validated 
                button: waka.support::ticket_w.trans.buttons.draft_to_validated 
                redirect: "close:1"
                fncs:
                    isCreatorAsking:
                        type: gard
            from: draft
            to: validated
