# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder tickettypes

# Attribute name
nameFrom: name

# Model Class name
modelClass: Waka\Support\Models\TicketType

# Toolbar widget configuration
#toolbar:
    # Partial for toolbar buttons
    # buttons: reorder_toolbar