# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.support::lang.controllers.tickettypes.label

# Model Form Field configuration
form: $/waka/support/models/tickettype/fields.yaml

# Model Class name
modelClass: Waka\Support\Models\TicketType

# Default redirect location
defaultRedirect: waka/support/tickettypes

# Create page
create:
    title: backend::lang.form.create_title
    redirect: waka/support/tickettypes/update/:id
    redirectClose: waka/support/tickettypes
    form: $/waka/support/models/tickettype/fields_create.yaml

# Update page
update:
    title: backend::lang.form.update_title
    redirect: waka/support/tickettypes/update/:id
    redirectClose: waka/support/tickettypes

# Preview page
preview:
    title: backend::lang.form.preview_title
