# ===================================
#  Btn  Behavior Config
# ===================================


modelClass: Waka\Support\Models\TicketType

workflow: false 

###BREADCRUMP
breadcrump:
    inSettings: true 
    indexUrl: waka/support/tickettypes
    indexlabel: waka.support::tickettype.title
    title: waka.support::tickettype.form_name

###TOOL_BAR
tool_bar:
    base:
        create: 
            show: true
            permissions: []
            url: waka/support/tickettypes/create
        reorder: 
            show: true 
            permissions: []
            url: waka/support/tickettypes/reorder
 
        delete: 
            show: true
            permissions: []
    config_btns:
            format: all
            btns:
    config_lot:
        format: all
        btns: 
    # partials: #Attention seul les variables modelId et modelClass (class du controller) sont disponible sans les partials.  
    #     testbtns:
    #         url: $/waka/support/controllers/tickettypes/_test_btns.htm

###ACTION_BAR Producteurs. Les behavior liée aux boutons doivent êtres instanciés implements = [waka.xxx.behaviors.yyy] dans le controller. 
action_bar:
    config_btns:
        format: grouped #unique : un seul bouton, all : tts les boutons
        groups:
            waka.utils::lang.prod.produce: oc-icon-file-text-o
            waka.utils::lang.prod.send: oc-icon-external-link
            waka.utils::lang.prod.tools: oc-icon-wrench
        btns:

    # partials: #Attention seul les variables modelId et modelClass (class du controller) sont disponible sans les partials.  
    #     name:
    #         url: $/waka/support/controllers/tickettypes/_test_update.htm
