# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.support::tickettype.form_name

# Model Form Field configuration
form: $/waka/support/models/tickettype/fields.yaml

# Model Class name
modelClass: Waka\Support\Models\TicketType

# Default redirect location
defaultRedirect: waka/support/tickettypes

# Create page
create:
    title: waka.support::tickettype.create
    redirect: waka/support/tickettypes/update/:id
    redirectClose: waka/support/tickettypes
    form: $/waka/support/models/tickettype/fields_create.yaml

# Update page
update:
    title: waka.support::tickettype.update
    redirect: waka/support/tickettypes/update/:id
    redirectClose: waka/support/tickettypes

# Preview page
preview:
    title: waka.support::tickettype.preview_name
