# ===================================
#  WakaController | Workflow | Productor |  Behavior Config
# ===================================


modelClass: Waka\Support\Models\TicketType
backendUrl: waka/support/tickettypes

workflow: false 


controllerConfig:
    breadcrump:
        inSettings: true 
        title: waka.support::lang.models.tickettype.label
        rows: 
            index: 
                label: waka.support::lang.controllers.tickettypes.label
                url: waka/support/tickettypes 
    index:
        base:
            create: 
                show: true
                permissions: [waka.support.*]
            reorder: 
                show: true  
                permissions: []
            delete: 
                show: true
                permissions: [waka.support.*]
        # partials:
        #     index_btn:
        #         url: $/waka/support/controllers/tickettypes/_index_btn.php
    update:
        # partials:
        #     update_btn:
        #         url: $/waka/support/controllers/tickettypes/_update_btn.php

 
reorder:
    title: waka.wutils::lang.global.reorder 
    # reorderRelations:
    #     model:
    #         title: Réordonner le {model} # Reorder Title
    #         nameFrom: name # Attribute name
    #         relationName: setups   # Model Class name
